### ISSUE TITLE
Crashes when trying to share KDBX file with it

### ISSUE THREAD

**Issue by rouben** [FrankHausmann/IOSKeePass#1]
Attempting to share file via "copy to IOSKeePass" function causes the app to crash. The original "MiniKeePass" did not have this issue. How can I help fix this?

**Steps to reproduce:**
1. Locate KDBX file in OneDrive or any other app.
2. Use "share" function. In OneDrive use the "share a copy" function to bring up the iOS share dialog. 
3. In the iOS sharing dialog, scroll the list of apps to the right until you find the "more" button with three dots:4. From the resulting list, select "copy to IOSKeePass" 

**Expected result:** file is transferred to the app.

**Actual result:** IOSKeePass crashes and you are taken to the iOS home screen.

**Comment by FrankHausmann** [comment]
thanks a lot for the issue.

In the next release it will be fixed, and sharing from remote will be removed in IOSKeePass.
The idea behind this is to not allow sharing from any one, the app should handle Data them self from any one who support.
Since IOS 11 there is a way to put and get files from file locations local and remote.

Pleas using this for get Files over IOS File Locations:
<img width="415" alt="Bildschirmfoto 2020-08-02 um 08 58 04" src="https://user-images.githubusercontent.com/67282017/89117550-dd3e7280-d49e-11ea-9cb4-07518c90a75e.png">
 
This Bar button opened the file Location. Change the Location to any app on your phone to support file location or on your Local storage, i using Apples iCloud and a private nextcloud. Both solutions support modern file sharing over IOS file location store point, and works as expected.

I know many people understand the new technology, and there missed understand rated with a lower rating.
If you think the App.

If you should think that this app should allow direct sharing of other apps except via the IOS file location, I would like to invite you to participate in this project free of charge in accordance with the rules of the Free software foundation.

**Comment by rouben** [comment]
Odd... that doesn't work for me. That is, I can copy the KDBX files to the app's folder on iCloud and Local storage, but the app does not show the KDBX in the list, even after I force it to close and relaunch it.

The workaround is like this:
1. First create new database of the same version (I used 2.x, since my DB is a KDBX) and use exactly the same password.
2. Go to local storage, delete new KDBX file from local storage of the app.
3. Copy the actual KDBX file you're trying to import to local storage of the app. Make sure filename and password match exactly to filename and password in step 1.

After doing the workaround above, I am able to open my existing KDBX file. It's minor annoyance, but other than that, the app works well.

Thank you for continuing to support this great app! There are many others on the app store, but they all are either paid and/or closed source, and I can't trust my passwords to closed source apps!

I look forward to the next release, and would be happy to test. Unfortunately I don't know much about ObjectiveC to be able to contribute code.

**Comment by FrankHausmann** [comment]
Thanks rouben, 

to describe a workaround, this will maybe help others. There is indeed an issue, i will fixed in the next release.
Also coming up, the app will support IOS Dark mode design.

On your comment "...and/or closed source...". 

I also think that it is the best app to store passwords securely and you can also open and maintain these files on all OS with open source projects. This is the reason why I will continue to maintain ISOKeePass (MiniKeePass) in my free time.

**Comment by rouben** [comment]
I confirm that the latest release on App Store fixes this issue. Thank you!
