### ISSUE TITLE
Support DataBases V4

### ISSUE THREAD

**Issue by Maximus1996** [FrankHausmann/IOSKeePass#11]
Hello,

First of all, thank you very much for the App. I really think it´s under appreciated and not known enough, despite it being free, open source and doesn´t hide features behind paywalls.
I would like to ask if there is any roadmap to support newer KeePass data bases version like 4. Because, for now, I use a DataBase from KeePassXC which uses version 4, the App will not load it and shows an error.

Thank you very much!

**Comment by FrankHausmann** [comment]
Hi,

Yes, I see the need to support the V4 DB as well. Since IOSKeePass is used by myself but is a pure hobby project, I can only work on it from time to time. Basically, only the "inner header" of the DB needs to be processed, then that's it.

If someone wants to help with the development or testing, I'm happy to hand it over.

**Comment by Maximus1996** [comment]
Thank you for the quick answer. Sadly, I do not possess the needed knowledge for the development, but if you need help with testing the App (something like the TestFlight Beta program for iPhones), it would be my pleasure to help!

**Comment by FrankHausmann** [comment]
Hi,

implementing of KDBX 4 is finished IOSKeePass and ready for Testing. 

I have complete changes to another open source library called KeePassKit also find on Github,
Thanks so mutch to the Contributiors of KeePassKit source code

- Michael Starke
- ChesterLiu
- MaximeEpain
- Jordan Sechler

but i don´t use there library i use the original source code inside IOSKeePass so that anyone review what is inside.

If you want send me your email address and your nick as first- and surname,so that i can registered you
to AppleStore Connect Testflight group member.

I expected small bugs but i am sure,that 98% will running error free
If you dont want send your data over this comment using fhausmann_at_unicomedv_dot_de

**Comment by Maximus1996** [comment]
Hi,
This is great news, thank you! I sent you an email to the provided email address.
Thank you again!
