### ISSUE TITLE
Absturz nach Bearbeiten

### ISSUE THREAD

**Issue by Caddode** [FrankHausmann/IOSKeePass#12]
Datenbankeinträge können nicht bearbeitet werden. Nach Fertig stürzt das Programm ab und speichert nichts. Aktuelles iOS. 

Leider keine Copy Funktion im Kommentare Feld. Man muss auf Bearbeiten, aber dann stürzt das Programm ab.

**Comment by FrankHausmann** [comment]
First of all, thank you for your comment.
Since IOSKeePass is used 55% in the US, it is important that we agree on the English language here, even if this is sometimes difficult for German (I am myself). 
On the subject of version 2.0.0 not being released yet, but only being made available for external testing, please excuse me. I have now removed IOS Keepass from the AppStore again, because especially with DBs that have more than 16 rounds in Argon2 hashing 3it comes to performance problems on the iPhone.


I don't know when I will release it again, as it is a hobby project.
