### ISSUE TITLE
Select / copy / cut / paste in "comments" section

### ISSUE THREAD

**Issue by El-Marti** [FrankHausmann/IOSKeePass#13]
For the moment, it is not possible to select/cut/copy/paste in the "comments" section.
Could you please fix this ?

**Comment by FrankHausmann** [comment]
First of all, thank you for your comment.

On the subject of version 2.0.0 not being released yet, but only being made available for external testing, please excuse me. I have now removed IOS Keepass from the AppStore again, because especially with DBs that have more than 16 rounds in Argon2 hashing 3it comes to performance problems on the iPhone.


I don't know when I will release it again, as it is a hobby project.

**Comment by El-Marti** [comment]
Hi, since 2.0.5 update, I can make appear the copy paste menu but it is not usable correctly  or almost unusable at all…. Was the fix included in this version ?

**Comment by FrankHausmann** [comment]
No, rudimentary it works before 2.0.0. For better handling a usable copy, paste must complete new redesigned.
tip: Go to editmode and touch longer than 2s, and copy,paste,append ios menu will open

**Comment by El-Marti** [comment]
You're right. But unfortunatly, it's completely unusable. I have lots of notes and I need to select only a part of it and with this method it does not work correctly. Thanks for your work :-)

**Comment by FrankHausmann** [comment]
Hi,

I have now completely restructured the editing of notes on a keepass entry, I now need a tester to test this. Since you seem to work with long texts it would be good if you do the testing.

If you agree, send me your email address, I will then enter you in the Apple AppStore as a TestFlight user. Apple will then send a link to this email for download.

**Comment by El-Marti** [comment]
Hi,

Yes, here it is !
***@***.*** 

Thanks for your work 👍

Eloi

>

**Comment by ilciano** [comment]
Hi Frank,
if you need another tester I'm also super interested in the copy/paste functionalities in the notes. thanks

**Comment by FrankHausmann** [comment]
Hi,

yes sure on the  next update i can doit, but at the moment the Comment Editor works very well, because i get
ioskeepass user notes, that the app crashed on editing notes. 
Not comprehensible for me without further information.

If you have also issue on this, please tell me, where the Kepass DB came from incl. Crypto algorythm, wich Iphone/IOS you use ?

This is important for me, so that io can take a look inside debugger on Simulator, to see whats going wrong.

**Comment by El-Marti** [comment]
Hi Franck, as you know, I use "notes" section a lot and sometimes, I write long text in it !
But when I just want to read it completely, I cannot scroll at the bottom without going in editing mode. 
Also, I cannot copy text without going in editing mode.

I would like to scroll, copy  without going in editing mode. Is it possible ? Thanks !

**Comment by FrankHausmann** [comment]
Hi,

At the moment I don't have time for that, because I have to earn my living with paid projects.

I think I will have time again in November.
Until then I ask for patience

**Comment by El-Marti** [comment]
Thanks for the last update. 
It would be perfect if we could select and copy text without being in editing mode. 🙂

**Comment by El-Marti** [comment]
Hi, I have noticed that to select a part of the text to copy it, we need to go in "edit" mode so we can make mistakes.
For the moment, we can only copy the entire "comment" section by clicking on it.

Is it possible to select & copy a part of this section without going in "edit" mode as we do it in Safari for example....  we can't modify the webpage but we can select a part of the text :-)
