### ISSUE TITLE
App store/TestFlight link

### ISSUE THREAD

**Issue by rouben** [FrankHausmann/IOSKeePass#15]
Hi,

Would it be possible to include a link to the app store, or how to get this app from TestFlight if it's on TeatFlight?

Thanks!

Rouben

**Comment by FrankHausmann** [comment]
If you want send me your email address and your nick as first- and surname,so that i can registered you
to AppleStore Connect Testflight group member.

After i reached your personal data and you are registered by me, you get an Email from Apple with link to the app
Please Test Encryptions and Algorithm that will help by long running encryption rounds for dummies users, there think after Open the DBs and nothing happend because while running the APP they closed the app.

After the the Core Test is done i will also released yubikey over NFC support for DBs (if i have enough time 😃 )
