### ISSUE TITLE
AutoFill extension

### ISSUE THREAD

**Issue by zilluss** [FrankHausmann/IOSKeePass#17]
Password managers on iOS can provide an extension to autofill passwords in Safari and apps. I'd like to implement this feature if I may.

**Comment by FrankHausmann** [comment]
Hello Martin,

since Keepass and its forks as well as IOSKeePass are a very secure repository for passwords and secrets, and they should stay that way, there are at least a few rules for IOSKeePass.

1.) Generally speaking, anyone with enough cryptography experience can join, or even developers who want to learn, but are not allowed to change the cryptography part. It is important that the compatibility of the KeePass DB's to other forks is guaranteed.

2.) Any change must be personally tested by the source code collaborator, simply for the reason that support requests are kept to a minimum.

3.) IOSKeePass is not only open source but also free for everyone and should remain so, it is not externally funded and there is no advertising (i hate advertising) or anything like that. the only idea is to make the IT world a bit more secure. This means that even if a developer wants to participate in this project, he/she will not be paid for his/her work, development, testing etc., the source code that is delivered and integrated is always either subject to another free open source license (Apache, MIT, GPL) if it is already open source, new developments are always subject to the GPL.

4.) Every extension must be security tested so that stealing passwords and secrets is almost impossible.

5.) Only after completion and testing of the new extensions may the repo be pushed to git remote.

6.) For IOSKeePass only Frank Hausmann is allowed to publish the APP "IOSKeePass" in the Apple AppStore.

Please send me an email to fhausmann at unicomedv.de in which you accept these rules. 

When I have received your confirmation email I will invite you as a collaborator to the IOSKeePass repo.

**Comment by zilluss** [comment]
This is more complex than I anticipated. Basically, the autofill extension is an isolated process that can't call the app directly but runs its own code. The only way to share data with the host app is to create an app group so the extension and the app can share files, settings and their keychain (similar to how the google maps app can share the login with google docs). This also goes for the code: In order to share code for the extension and the app, it needs to be extracted into a shared framework. To keep the changes to a minimum I suggest the following:

- Create an app group in which the database and key files are stored. This way both the app and the extension can access the files.
- Create a shared framework that contains the bare minimum shared functionality (e.g. PIN/Biometrics check and handling keepass files).
- For the first implementation I would keep the UI as a simple list of matching entries (So no search bar, icons or database file picker)

**Comment by FrankHausmann** [comment]
Hi Martin,

for your suggestions and comments, and that you deal with this issue.

Before I deal with the topic of App Groups and shared data in it myself, I would like to point out again that just by not sharing master keywords in conjunction with keyfiles and the methodology of how keepass writes the xml data, a relatively small area for attacks is available.

See also the article by Stuart Schechter.
https://stuartschechter.medium.com/before-you-use-a-password-manager-9f5949ccf168

I think in principle this is possible, but I would rather recommend in the framework you have in mind, no direct exchange of keyfiles and master passwords because this also requires the HostApp.

We should rather think about Inter-process Communicaton
see here:
https://nshipster.com/inter-process-communication/
and here
https://ddeville.me/2015/02/interprocess-communication-on-ios-with-mach-messages/

**Comment by zilluss** [comment]
Thanks for the quick reply. There is no guarantee that the host app is running when the extension is invoked, so the extension not supposed to communicate with the app directly via IPC. The "correct" way is to share the keychain and database files across app and extension (which still leaves them sandboxed). This is the approach I saw in other open source password managers as well (Keepassium for example). Then the extension decrypts the database the same way the app does, after authenticating the user via password, pin or biometrics. I would exclude databases with key files from the extension until I figured out the best way to handle them in the UI. For now I think it would be enough to get the extension running with plain databases.

**Comment by El-Marti** [comment]
Hi, the feature works but for this, I have to modify each entry to enable autofill. Is it possible to enable it for all entries in one button ??

**Comment by FrankHausmann** [comment]
For now, I have handled this individually for each entry so that the user has control over what is stored in the store (SQLite DB) with AES256 encryption and what is not. For the next update, I will build another switch that will give the user the choice of handling everything or individually.

**Comment by El-Marti** [comment]
Ok perfect :-)
Thank you so much for your work.

**Comment by El-Marti** [comment]
Hi, I have enabled "AutoFill" for entire database but the pop-up appears every time I open a database. And I have to confirm each time. Is it a know issue ?

**Comment by FrankHausmann** [comment]
hi yes the process is a little confuse, but if you consider the following it works as expected.

turning on the AutoFill support switch and selecting All Keepass entries per DB
causes that when opening a KeePass db file it asks if the user wants this at all after confirmation all accounts of this opened db are stored encrypted in a SqLite db including AES256.
If the switch is set to 0 again, this Autofill.DB is deleted, but note that the other account data from other Keepass DBs are no longer available because the SqLite DB file from the Iphone APP sandbox.

But don't worry, by turning on the switch, the dumping of the account data will start again when opening the kdbx.

**So now the turn arround for your question.**
Switch Autofill support to ON and All Keepass entrys, open all DB's one after the other which should get the Autofill support and answer the security question with Accept, after all go to Settings and set the section botton to invidual, after that you will not be asked anymore but all your desired account data will be available for the Autofill.
But be careful, if your passwords change, you have to synchronise the individual with switch off switch on in the Keepass entry with the SQLite DB.

Another hint: the SQLite DB of the autofill function is encrypted with AES256 and salt and pepper. And no one but myself knows the salt (publickey) and pepper (privatekey) so if it becomes possible to access the sandbox files (Apple plans this in future IOS versions) the account data in the autofill mechanism will remain secure.

**Comment by El-Marti** [comment]
Thanks ! It works 🙂
Just another suggestion without link with it but with the « notes » section.

I have long, very long notes sometimes and the only way to scroll down is to switch in « edition mode » and tap on the notes section to be able to scroll down.

Could you please make possible the scroll down in notes without editing the entry ?

Thanks a lot 🙂

Éloi 

Envoyé de mon iPhone
