### ISSUE TITLE
Iphone databank kann nicht mehr geöffnet werden

### ISSUE THREAD

**Issue by DaHans60** [FrankHausmann/IOSKeePass#18]
Ich wollte die kdbx kopieren und habe zwischen der app ioskeepas und der App Dateien hin- und hergewechselt
Jetzt kann ich die Datei nicht mehr öffnen. Ich sie zwar unter Dateisuche sehen aber nicht kopieren und nicht öffnen. Applesupport meint es liegt am Passwortschutz der Datei
Bin da ratlos. Hat jemand eine Idee ?

**Comment by FrankHausmann** [comment]
Hi,

Did you create the Keepass DB on the iPhone or import it from your MAC or Windows desktop?

Please check if the file is larger than 1024 bytes.

Please share the file via email, iCloud, Nextcloud with your MAC or PC, and open it with MacPass, Keepass, KeepassXC (all freeware) etc. and enter your master password or keyfile.

When this opens, move the file to Icloud, delete your entry in IOSKeepass and re-import the file from ICLoud into IOSKeePass using the import button at the bottom centre.

If this does not work, the master password has probably been entered incorrectly. (Please have a look at your language and region settings) different keyboard e.g. English instead of German for special characters).

Good Luck.

**Comment by DaHans60** [comment]
Hallo,
Ich vermute mal, dass Sie Deutsch sprechen.
Das Problem war, dass die Datei unter suchen angezeigt wurde sich aber nicht kopieren lässt.
Die Datei hing irgendwo im Nirwana.
Wie das passieren konnte verstehe ich nicht.
Ich habe sie definitiv nicht gelöscht. Ich bin nur zwischen der iOS-App und der KeypassApp hin und hergesprungen.
Auf einmal war das Ding weg.
Der Support hat mir empfohlen das neueste IOS zu installieren und jetzt kann ich sie auch nicht mehr sehen
Das Dateihandling unter IOS ist schon irritierend
Was soll’s, habe noch handschriftliche Aufzeichnungen
Danke auf jeden Fall für ihre Antwort 
Grüße 
Hans Böttcher 

Von meinem iPhone gesendet
