### ISSUE TITLE
See and add attachements in the app

### ISSUE THREAD

**Issue by El-Marti** [FrankHausmann/IOSKeePass#21]
Currently, when I want to add or use an attachement in the database, I use my PC. But it would be great if I could do these 2 actions directly from iOS ! Is it technically possible ? Thanks for you excellent job.

**Comment by FrankHausmann** [comment]
First of all, yes, it is also possible to view and add attachments to a KeePass DB in IOS.

BUT:
1.) A Keepass DB file is an XML file encrypted with the respective chosen algorithm, an attachment is a data tag within the XML and stored there as BASE64 to not break the XML format. This means that the KEEPASS DB must be completely loaded into memory and decrypted there. Since iPhones, IPADs etc. do not have an external DISK for swapping RAM, an out-of-memory situation can occur, especially on devices with little memory. 

2.) The Apple ARM CPUs are fast, but whether it is fast enough to open large KeePass DB files with many attachments in a reasonable time before a user thinks stupid IOSKeepass can't open my file I don't know.

3.) Another point is that not all file formats are supported by desktop computers on IOS and there may be high support requests in the form of "IOSKeePass can't open my file".

Maybe it is possible for you to run a test where you build a KeePass DB that has the following sizes (10MB, 50MB, 100MB, 500MB and 1GB) and tell me what CPU you have in the IOS device and how long it took to open it. After this test, we can consider whether an implementation of attachments makes sense or not.

**Comment by El-Marti** [comment]
If I speak about my own case, my DB are between 200 and 500 Ko. I have essentially  .png or .jog  files in attachement, perhaps some small zip files but it should not be very large !

**Comment by El-Marti** [comment]
Thanks for this feature, you really make a great job :)
Is it possible to add a rename option in order to change the filename (for example when we add a picture from Camera roll, we would like to customize the name).

Regards :)
