### ISSUE TITLE
Crash when saving after comment edit in 2.3.0

### ISSUE THREAD

**Issue by El-Marti** [FrankHausmann/IOSKeePass#28]
Hi,

I have just updated the app in 2.3.0.

1) I encounter app crash when I want want to click on OK after editing comments. I have reinstalled  the app but it does not fix it. The strange thing is that I have successfully done it only once. After, I have systematically crashes.

2) When we click on the comment section without being in editing mode, we automatically switch in edit mode. It could be « dangerous » when we just want to copy a part of the text.

Best regards.

Eloi

**Comment by FrankHausmann** [comment]
Hi,

first, thanks also from the (IOSKEEPASS, MiniKeePass) community for the explanatory comments and topics.

to 1.) Sorry I forgot to check in EntryController if I am already in edit mode, I fixed the bug in version 2.3.1, and uploaded to the APP Store.

to.) 2 There is actually no risk, because the entry goes into edit mode only if the text comparison between the text in the text editor is not equal to the text of the entry. Also, the text editor never saves the KeePassDB, this is only done by the entry editor through user interaction, either he clicks Finish (save) or he clicks Cancel (the edited entries are discarded).
In addition, the user has at any time the possibility to slide up the TextEditor to dismissen (close) it at any time. 

Cheers

**Comment by El-Marti** [comment]
Hi,

Thanks for the quick fix. Everything works fine now.

Isn’t it possible to copy text without opening the comment section ? Just by selecting text in view mode without clicking on it before so no risk to enter in edit mode.
Currently, a long press on the comment section does nothing. I need to click on it to be able to select text.

Best regards,

Eloi 


Envoyé de mon iPhone

**Comment by FrankHausmann** [comment]
Hi,

No copy of Text inside comment section causes too many errors.

The text editor is a very powerful tool which unfortunately cannot be integrated directly into the comment section, as this would require a complete redesign of the EntryViewController, for which I currently have too little time.

**Here again is the really simple operation of the text editor**

- A simple tap in the free space puts the cursor at the position to write.
- A simple tap on a dictionary reads the dictionary for replacement words and displays them in a header menu.
- A double tap opens the header menu for copy paste share etc., as well as the range in the text to increase or decrease the range.


In the end, it is no longer a LongPress but a tap to open and a double tap to select.

When I have a lot of time I will redesign the comment section.
