### ISSUE TITLE
Can‘t Open Database

### ISSUE THREAD

**Issue by quailegg** [FrankHausmann/IOSKeePass#3]
Hello, 
i can create a new database but not open it. also existing one could not be opened. Seems touch on database file doesn‘t call any action.

System is iPadOS 13.7 on iPadPro2020

**Comment by FrankHausmann** [comment]
Hi,

it looks as if touch / face id and / or pin were switched on in the settings, please switch them off first, create DB or import, open and close once with a known password, then switch on again if you want, then it works.

I'll leave the issue open because it has already happened to several users.

**Comment by quailegg** [comment]
Hi, switching settings doesn‘t change anything.

**Comment by FrankHausmann** [comment]
Hi yes,
debug session in xcode on Simulator Ipad Pro 12,9" 4 gen,bring followinf messagr.

_IOSKeePass[16590:893078] [AutoFill] Cannot show Automatic Strong Passwords for app bundleID: de.unicomedv.IOSKeePass due to error: iCloud Keychain is disabled_

i will fixit asap.

Thanks for comments, every comment will it make better

**Comment by quailegg** [comment]
Hi, 

the App is working now as expected. Thanks for the update and your work!
