### ISSUE TITLE
Favicon Support

### ISSUE THREAD

**Issue by matthiasballreich** [FrankHausmann/IOSKeePass#32]
Would be nice to have support to display the favicons:
- inside the imported / synced database
- get favicon from url when creating a new entry

**Comment by FrankHausmann** [comment]
Where to display the favicon from url. inside the KeePass Entry?
or as addition, custom field inside the entry.

At the moment we have an static Image list inside for dynamically images, the is a a little bigger redesign on it.
Technical that is not a beag deal, but it cost time (my free time).

**Comment by matthiasballreich** [comment]
Inside the Databaselist (Entries). By default there is shown a yellow key and if i go into the entry in the tile filed the same icon is displayed. On both places the favicon of the url should be shown or if i use an imoprted database which i have prefilled from keepass or keepassXC on my machine.

It is just a Feature-Request or Improvement Idea ;) if you did not have the time, etc. then it is so.

**Comment by FrankHausmann** [comment]
Have now reworked the support for custom icons in IOSKeePass without redesigning the whole thing.

Custom icons are added to the list of standard icons when opening the DB, custom icons are only available for the DB and not for other DBs.

I have implemented a website favicon exctrator, which works as follows.

In non-editing mode click on the icon next to the title, then the icon changes if a favicon on the webserver could be extracted as specified in the texfield url (works in 98% of all cases).

After the title entry icon has changed, go into editor mode and close the window, now the cuszom icon is added to the DB, now please open again and select the new icon and save again.

Sorry for the cumbersome process, but had to upload the update due to bugs on the ipad.
