### ISSUE TITLE
IOSKeePass 2.3.5 very sluggish on iPad Air 2 under iPadOS 15.4

### ISSUE THREAD

**Issue by fcprindle** [FrankHausmann/IOSKeePass#33]
I have not seen this issue mentioned elsewhere, so I respectfully submit it here in hopes that a solution or workaround can be identified. Whenever I run IOSKeePass 2.3.5 on my iPad Air 2, everything about it is sluggish: getting the password dialog after tapping the kdb file takes many seconds; each key entry in the password takes a second or more; getting the list of groups after entering the password takes several seconds; getting the list of entries in a group takes several seconds after tapping the group name, etc. The delays are not consistent, but always enough to be annoying. It's almost as if it's given a very low priority by the OS. And it's not just on iPadOS 15.4, but the same sluggishness was seen under iOS 13.6.

Surely someone else must be seeing this issue. It doesn't make IOSKeePass unusable, but it does make it hard to use after having used MiniKeePass on the iPad for years with virtually no lag.

**Comment by FrankHausmann** [comment]
Thank you for the feedback. The behavior even on an Ipad 2 is no different than on more modern Apple devices such as Iphone 11,12,13. this was tested with the settings below.

I suspect here a problem with the encryption (AES,ChaCha or TwoFish) and the associated algorithms (AES, Argon2d, Argonid) as well as the used rounds, threads and repeats.

See also the properties of your KDB (ButtonBar wrench icon).

Depending on how the KDB was created and works quickly on a MAC or Windows PC, e.g. on an Ipad Air more than 10000000 rounds and more than 2 threads could keep it very busy with calculations.

I recommend the KDB on an Ipad AIR 2 with these settings

<img width="50%" alt="Bildschirmfoto 2022-03-26 um 17 19 44" src="https://user-images.githubusercontent.com/67282017/160248385-ae422de8-71e2-4c7a-ab87-76a6eda2062f.png">

Note: The faster the Apple devices are the higher the encryption parameters can be set.

**Comment by fcprindle** [comment]
Thank you for that insight Frank. But I think your suggestion about slow encryption/decryption is not the cause of the sluggishness. First of all, note that my KDB file is generated by KeePass 1.23 running on Windows 10, which has (by default) the rounds set to 300 (see attached screenshot from iPad Air 2), so this file should encrypt/decrypt quite quickly. Second, the sluggishness is apparent even before any ongoing decryption is required; by simply starting the app (which then shows keepass.kdb as its only database) and then tapping on **keepass.kdb**, there is always a delay of from 2 to 30 seconds before the password dialog box comes up; then, while entering the password, taps on the keyboard to enter the password are delayed about 1/4 second to 1 second each; then when enter is pressed it takes several seconds for the categories to appear.

Now you know the software internally, so you may say that decryption is required from the instant **keepass.kdb** is tapped, but then I go back to my argument that the decryption load should not be that great with on 300 passes. Also the file at 212KB is relatively small.

Perhaps the sluggishness has something to to with your KDB file being Kdbx 3.1 and mine being Kdb 3.3. If I had to guess, from a software engineer's perspective, what is causing the sluggishness, I would suspect the IOSKeePass app is doing some sort of busy wait rather than relinquishing the processor during its idle time, thus causing the OS to lower its priority when it is not idle (but that's totally a guess)
![IMG_0258](https://user-images.githubusercontent.com/68157300/160286537-cc0b83f5-da26-4bc5-8b63-0ed80e2533cf.jpg)
.

**Comment by FrankHausmann** [comment]
This is not quite correct, even KeePass 1.23 from 2012 defaults to 6000 rounds, I just tested this on my Windows 11 machine and created a KDB 3.3 and then opened it with the Ipad Air 2 in the Mac Simulator without delay, edited entries etc.

They did not disclose that they were using an old KeePass.

Dominik Reichl developer for Windows Keepaas 1.x and KeePass 2.x has completely redesigned the data format from kdb to kdbx already in 2007.

To solve your problems I recommend the following procedure

Get the latest KeePass2 version 2.50 from january 2022 from https://keepass.info/download.html. Proceed as follows to migrate from KDB to KDBX
Select in KeePass2 the import there the KeePass 1.x and save afterwards in the KDBX format. You can also simply import the KDBX into IOSKeePass.

It would be nice to get feedback on whether this worked, so that other IOS users can use your information.

To get support for KeePass on Windows please contact Dominik Reichl https://keepass.info

Thanks


![grafik](https://user-images.githubusercontent.com/67282017/160294700-f8c93d34-75e8-499d-b593-3e05ec3e6349.png)

**Comment by fcprindle** [comment]
Frank, I went through that whole process you outlined for Windows, creating a .kdbx database with KeePass-2.50 with AES (6000 iterations per your recommendation) and importing everything from the older .kdb file. I then copied that new .kdbx file to the iPad and opened it with IOSKeePass.

Unfortunately I am seeing **exactly the same delays and sluggishness**, which again leads me to the conclusion that this does not have anything to do with the encryption. Just to be sure it wasn't a bad download of IOSKeePass, I deleted the app and re-installed it from the Apple Store. Re-imported the .kdbx file. Still same delays and sluggishness, no change.

In fact, with both the .kdb file and the .kdbx file imported to IOSKeePass (or with NO files imported at all), if I simply (from the main screen "Files") tap the + in the lower right corner, it takes 10 seconds before the "New Database" dialog appears. If I then tap "Cancel" in that dialog box, it takes 5 seconds before the dialog box disappears. I don't see how such delays could be explained by encryption/decryption time, since that has nothing to do with encryption/decryption. No other app on this iPad (and there are many) shows any such sluggishness/slow response, so it's not the iPad.

**Comment by FrankHausmann** [comment]
Sorry for the misunderstanding, I did not claim that it has anything to do with the encryption of the kdb but because I had this issue before on another device.

In the hope that I can help somehow please send me your settings from IOSKeePass, and tell me if you see in the topbar left a small cloud as an indicator.

Please understand that I do not answer immediately, because this is a hobby project from which no profits are earned.

**Comment by fcprindle** [comment]
Hi Frank. I respect that you maintain this program as a hobby and make no demands whatsoever of you. This is strictly for my education and to pass something along that may help other users should they come across this situation.

I have researched this significantly today and found a couple of interesting things I thought I'd share:

1. I happened to notice that although my database contains 179 entries, it also contained 393 entries in the "Backup" group, created automatically by KeePass every time I changed or deleted any other entry. Since I didn't need these, I deleted the Backup group reducing the total number of entries from 572 to 179. I then downloaded that to the iPad and opened it with IOSKeePass. I found that the delays, while still noticeable, were much shorter, and I can now live with them; so I've found a workaround (but not an explanation).

2.  I used Windows KeePass to create a new test database with 600 rather large (virtually identical) entries (I put a lot of text in the notes). IOSKeePass could deal with that one with no problem, no delays, no sluggishness regardless of whether I set the rounds to 6000 or 300. This implies that there is something "unique" about my **real** database that is causing the problem. Perhaps it's just one entry with something unusual in it that IOSKeePass is getting stuck on. It must be a function of the entries themselves and not the database because importing those entries into an empty .kdbx database results in the same delays.

3. The problem is what I'll call "persistent". That is, if I open the test database, there are no delays. If I then open my **real** database, I see the delays. If I then go back and re-open the test database, I see the same delays. It is as if something (a thread perhaps) gets left behind running on behalf of the **real** (slow) database and doesn't go away when I open the test (previously fast) database. The only way to get the test database to open again without delays is to terminate the IOSKeePass app (swipe up on home screen from the bottom to expose all previously run apps and swipe IOSKeePass up off the screen); then IOSKeePass will open and read the test database without delays until such time as I open my original database.

4. So I have a suitable workaround but can't identify what about my database is causing the problem nor can I create another database that replicates the problem. Since I obviously can't send you my database, I guess there is just no way to ever find the cause. I'll just use the workaround (periodically delete the Backup group to reduce the total number of entries).

Thank you for your help.

**Comment by FrankHausmann** [comment]
That's a lot of information, but the easiest way to find the error would indeed be an XCode debug session with your original file.

However, I would not give anyone my Keepass file. Since I am interested in this bug fix myself, there might be another way.

I use FlexTools in my debug version which displays pretty much every byte on demand as an InApp debugger on the IOS devices. Unfortunately I can't publish it in the AppStore because Apple has something against it for understandable reasons. However, I could register you as a tester of a preview in the Apple AppStore Connect to provide you with a version with the FlexTools.

You can find out what FlexTools are here:
https://github.com/FLEXTool/FLEX

If you would like to become a tester, I will need an email address which I will then enter in the AppStore Connect and you will then have to confirm this entry by email.

**Comment by fcprindle** [comment]
Frank, what you suggested is rather daunting since I have no experience in debugging iOS apps. So instead, I managed to create a fully sanitized database that exhibits the delay/sluggishness bug. I did this by deleting most of the groups and entries in my database and changing the usernames and passwords of the remaining ones to "ggggg". Then, to accentuate the delays, I duplicated the entries a number of times to create a database with 248 entries (the delay seems to be proportional to the number of entries).

So here you go - debug away! The master password is "test": [baddb.zip](https://github.com/FrankHausmann/IOSKeePass/files/8401240/baddb.zip)

**Comment by FrankHausmann** [comment]
Thanks a lot for your prepare on Test DB.

I found the Bug inside reading Meta Data on DB, this happend on old entrys.
Inside The Class **KPKTimeInfo inherited from NsObject** there is an Overwrite
for **IsEqual:Id**

The data in the fail db (meta data) causes a buffer overflow which leads to all memory objects pointing to the same IsEqual method and thus a constant validation of the objects takes place which fails because they are not KPKTimeInfo objects. This also explains why after the first opening it becomes more and more tedious as new objects are created and these are repeatedly validated incorrectly.
I have replaced the IsEqual:ID method with a direct comparison, so overwriting the IsEqual method is no longer possible and IOSKeePass runs as quickly as usual.

**But important!**
The buffer overflow is triggered by metadata that has not been decompressed correctly with gzip. Since other KeePass systems are written in C++ or C#, it will run differently there and may not cause buffer overflow.

I strongly recommend creating a new DB if you haven't already done so, as a buffer overflow or memory leak can always be exploited by attackers.

This will be fixed in the next version.

**Comment by fcprindle** [comment]
Could you give a specific example of metadata in the example that has not been decompressed correctly with gzip? Why would this metadata be in my DB? The DB was originally created by Windows KeePass-1.23.

**Comment by FrankHausmann** [comment]
No, for me the topic is closed and researching the past of older file formats makes no sense.

**Comment by fcprindle** [comment]
Version 2.3.7 works just fine now. Thank you so much.
