### ISSUE TITLE
PIN does not work like expected

### ISSUE THREAD

**Issue by GitOTR** [FrankHausmann/IOSKeePass#5]
I am on iOS/iPadOS 14. I activated PIN usage in iOSKeePass. In MiniKeePass I was prompted immediately after start to enter my PIN. With iOSKeePass the PIN prompt will only happen when I open the database file. 
Activating FaceID at the same time will habe the issue that I do not have to enter my master password for database. 
I would prefer the solution of MiniKeePass that the PIN protects the app start and I have to enter my master password afterwards when I open the database.

**Comment by FrankHausmann** [comment]
Now i fixed, but there is a little bit different from the original.
The reason laying on newer IOS versions and the mixed mode on Swift and Object-c source

Next weekend i upload it to App Store

**Comment by GitOTR** [comment]
I just updated to the last version. It is still possible to open the app without having to enter the PIN. Does not matter whether I use numeric PIN or Face ID.
If I disable Face ID the PIN is even not required before entering the master password. With Face ID before I can enter the master password Face ID is called.
What is the expected behavior for the PIN usage now? You wrote that there are changes to prior implementation in MiniKeePass.

**Comment by FrankHausmann** [comment]
Yes, that's right IOSKeePass is no longer a 100% fork in the area of ​​authentication, as ioskeepass aims to guarantee the modern and efficient way of unlocking via biometric support in order to make it as easy as possible for the user. The pin no longer replaces the master password, but the fingerprint and facial recognition do. Apple is more advanced than any other in terms of biometric recognition and authentication. In the original version, the master password was saved in the keychain using the pin and the DB was unlocked with a comparison using the pin. Now the PIN is only used to protect the unlocking of the app in the background.If the biometric comparison fails or does not exist, or has been switched off by configuration, the app is protected with a pin when it is retrieved from the background, provided this is in the configuration is switched on. I do not think that I will go back to replace a master password with a pin, if necessary to delete the database if too many incorrect entries were made for the pin. For data protection reasons, an APP must never delete user data, even if that might be a security criterion.

**Comment by GitOTR** [comment]
I do not want to replace the master password with the PIN. I used both security methods.
The PIN to unlock the app and afterwards the master password for unlocking the database. I never saved the password for the database in the keychain. Only for the PIN I used Face ID. 
Apple also provides the possibility to delete the phone after unlock failed for several tries. Although this feature is not that important for me like the possibility to secure app and database separately.
