### ISSUE TITLE
Requires iOS 13 or newer?

### ISSUE THREAD

**Issue by DaSandman** [FrankHausmann/IOSKeePass#8]
I was heartened and grateful to find the iOSKeePass app available as an open source KeePass database alternative.  The app claims to be a fork of the now retired open source MiniKeePass.  However, disappointment soon followed when the AppStore noted that it required iOS 13.  I find that development choice baffling considering MiniKeePass, KeePassium, Strongbox, & others all run on older devices and much older iOS versions, including my own iPhone 6 (iOS 12.5), with iOS versions as old as 9 (Strongbox).  KePassium, among the newest KeePass apps for iOS only requires iOS 11.  Please consider lowering the OS requirement to allow older devices to enjoy and appreciate your work on iOSKeePass.  Kind regards.

**Comment by FrankHausmann** [comment]
yes it is correct that ioskeepass requires an IOS 13.1 or higher, and possibly other password protectors use a different IOS version without going into the depths of why ioskeepass requires an ios 13.1. I recommend you take the source code and build something yourself for your older IOS versions. I myself will not downgrade ioskeepass, but only support the latest IOS versions, the reason is also due to many requests from users who want to use new features from newer IOS versions. Since, as you yourself say, there are a large number of KeePass variants in the Apple Store, you have the free choice of which app you want to protect your passwords with, or you can build again yourself.

To everyone else, please save me such inquiries, this project is a pure hobby, it does not cost you anything, accept it as it is, or look for something else.
The ways are varied, as you read.

with kind regards
